### ISSUE TITLE
How to cancel pull request?

### ISSUE THREAD

**Issue by 5731005321-KI** [2110215-ProgMeth-2015-1/2110215_Exercise0_HelloGitHub#116]
If I do a pull request, and later want to cancel it (maybe because I've found I bug after doing so), how can I do that?

**Comment by pakaponk** [comment]
You don't have to cancel a pull request to send a new version (the version without bug), just commit the new version.

I alway see the latest version of your assignment project in the pull request

**Comment by 5731005321-KI** [comment]
Thank you. :+1:
